#!/bin/sh
set -e

echo "***************************"
echo "Running git pre-commit hook"
echo "***************************"

# Run to make sure there is no lint issue
./gradlew ktlintCheck

RESULT=$?

# return 1 exit code if running checks fails
[[ ${RESULT} -ne 0 ]] && exit 1
  exit 0

exit 0